### ISSUE TITLE
Use single file for synonyms

### ISSUE THREAD

**Issue by arnikz** [PBR/QTM#33]
Currently, there are four copies of the `synonyms.txt` file in Solr cores:

```
./propTerms/conf/synonyms.txt
./statoTerms/conf/synonyms.txt
./solaLyco2/conf/synonyms.txt
./terms/conf/synonyms.txt
```

Use symlinks? Modify [this](https://github.com/PBR/QTM/blob/master/src/main/java/solrAnnotator/AbbrevtoSynonyms.java) code (lines: 28-32) to work with X Solr cores

**Comment by gurnoor1990** [comment]
Closed with #37
