### ISSUE TITLE
Clarify column content

### ISSUE THREAD

**Issue by arnikz** [PBR/QTM#55]
_annot_ column of the _COLUMN_ENTRY_ table:
example record: `http://purl.obolibrary.org/obo/STATO_0000123|R2|r2|r2|0|2|8a0aaea1-4599-4513-88fd-d209188cf4e0`

Please clarify what the different values (sep by '|') are (ontology URI | ... )

**Comment by arnikz** [comment]
we decided to trim after URI

**Comment by gurnoor1990** [comment]
Yeap. So the COLUMN_ENTRY output should be like this
col_id	tab_id	header	type			annotate     
1		1	Trait		QTL descriptor	(null)
2		1	H2		QTL value		(null)
3		1	Min		QTL value		http://purl.obolibrary.org/obo/STATO_0000150
4		1	Max		QTL value		http://purl.obolibrary.org/obo/STATO_0000151
5		1	Mean	QTL value		http://purl.obolibrary.org/obo/STATO_0000230
6		1	CV%	QTL value		http://purl.obolibrary.org/obo/STATO_0000236
