### ISSUE TITLE
Remove trailing spaces

### ISSUE THREAD

**Issue by arnikz** [PBR/QTM#61]
The values stored in the _marker_, _marker_uri_, _gene_ and _gene_uri_ columns (_QTL_ table) contain trailing spaces.

**Comment by gurnoor1990** [comment]
Trailing spaces are not in the database, they are coming only in the csv viewfile. @arnikz, do you know a simple solution to this with reading and editing the file? 

bash -c sqlite3 -header -csv qtl.db "SELECT * FROM V_QTL" >qtl.csv

**Comment by arnikz** [comment]
I'm not sure which db file(s) are you looking at. Both tomato/potato dbs (as released [here](https://doi.org/10.5281/zenodo.1215044)) have this issue. See, for example, the `marker` column:

`sqlite3 tomato_QTLs.db "select \"'\" || marker || \"'\" from QTL"` gives

```
'TG167_Y02_52393366 '
'Y04_03230589 '
'Y04_53862540 '
'Y04_61146494 '
'Y07_67908188 '
'Y07_64327204 '
'Y08_57208257 '
'Y08_57208257 '
```
and
`sqlite3 potato_QTLs.db "select \"'\" || marker || \"'\" from QTL"` gives

```
'InvGE-C2475454T '
'InvGE-G2475344Ad '
'InvGE-C2475295A '
'InvGE-G2475187A '
'InvGE-G2475187A '
'InvGE-G2475187A '
'SssI-C45711901T '
```
Clearly, there are extra spaces in the lines.

**Comment by arnikz** [comment]
Fixed for the `marker` and `gene` columns but not for `marker_uri` and `gene_uri`. You could use  e.g. `PMC4579088`, `PMC4969537` and `PMC5145867` for testing.
