### ISSUE TITLE
Make --config as a compulsory argument.

### ISSUE THREAD

**Issue by gurnoor1990** [PBR/QTM#74]
Presently it is set default to config/config_tomato.properties

```
parser.addArgument("-c", "--config").help("conifgration/property file").setDefault("config/config_tomato.properties");

```

**Comment by arnikz** [comment]
`--config` does not have to be mandatory, what about setting default value (filename) e.g., `config.properties`?

**Comment by gurnoor1990** [comment]
Yes, that was already done!
